# NAMESPACE: promptads-app
# This file serves confidential information about the system.
# Having secrets in separate files allows to hide delicate information from the project.

apiVersion: v1
kind: Secret
metadata:
  name: promptads-secret
  namespace: promptads-app
type: Opaque
data:
  DATABASE_PASSWORD: PromptS@les2025 
  REDIS_PASSWORD: PromptS@les2025
